# Generated by Django 4.1.7 on 2023-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_alter_solarpanel_canton_alter_solarpanel_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='canton',
            field=models.CharField(choices=[('USK', 'Unsko-sanski'), ('POS', 'Posavski'), ('TUZ', 'Tuzlanski'), ('ZDK', 'Zeničko-dobojski'), ('BPO', 'Bosansko-podrinjski'), ('SBK', 'Srednjobosanski'), ('HN', 'Hercegovačko-neretvanski'), ('HB', 'Hercegbosanski')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='zone',
            field=models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], max_length=50),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='canton',
            field=models.CharField(choices=[('USK', 'Unsko-sanski'), ('POS', 'Posavski'), ('TUZ', 'Tuzlanski'), ('ZDK', 'Zeničko-dobojski'), ('BPO', 'Bosansko-podrinjski'), ('SBK', 'Srednjobosanski'), ('HN', 'Hercegovačko-neretvanski'), ('HB', 'Hercegbosanski')], max_length=100),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='zone',
            field=models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], max_length=50),
        ),
    ]
