# Generated by Django 4.1.7 on 2023-03-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_remove_solarpanel_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Unsko-sanski'), ('POS', 'Posavski'), ('TUZ', 'Tuzlanski'), ('ZDK', 'Zeničko-dobojski'), ('BPO', 'Bosansko-podrinjski'), ('SBK', 'Srednjobosanski'), ('HN', 'Hercegovačko-neretvanski'), ('HB', 'Hercegbosanski')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='entity',
            field=models.CharField(choices=[('RS', 'Republika Srpska'), ('FBiH', 'Federacija Bosne i Hercegovine'), ('BD', 'Brčko distrikt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='canton',
            field=models.CharField(blank=True, choices=[('USK', 'Unsko-sanski'), ('POS', 'Posavski'), ('TUZ', 'Tuzlanski'), ('ZDK', 'Zeničko-dobojski'), ('BPO', 'Bosansko-podrinjski'), ('SBK', 'Srednjobosanski'), ('HN', 'Hercegovačko-neretvanski'), ('HB', 'Hercegbosanski')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='entity',
            field=models.CharField(choices=[('RS', 'Republika Srpska'), ('FBiH', 'Federacija Bosne i Hercegovine'), ('BD', 'Brčko distrikt')], max_length=50),
        ),
    ]
