# Generated by Django 4.1.7 on 2023-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_solarpanel_creation_date_solarpanel_last_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='canton',
            field=models.CharField(blank=True, choices=[("('USK', 'Una-Sana Canton')", 'Usk'), ("('POS', 'Posavina Canton')", 'Pos'), ("('TUZ', 'Tuzla Canton')", 'Tuz'), ("('ZDK', 'Zenica-Doboj Canton')", 'Zdk'), ("('BPO', 'Bosnian-Podrinje Canton Goražde')", 'Bpo'), ("('SBK', 'Central Bosnia Canton')", 'Sbk'), ("('HN', 'Herzegovina-Neretva Canton')", 'Hn'), ("('HB', 'Herzeg-Bosnian Canton')", 'Hb'), ("('SA', 'Sarajevo Canton')", 'Sa'), ('ZHK', 'Western Herzegovina Canton')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='entity',
            field=models.CharField(choices=[("('RS', 'Republic of Srpska')", 'Rs'), ("('FBiH', 'Federation of Bosnia and Herzegovina')", 'Fbih'), ('BD', 'District Brcko')], default='entitet', max_length=50),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='canton',
            field=models.CharField(blank=True, choices=[("('USK', 'Una-Sana Canton')", 'Usk'), ("('POS', 'Posavina Canton')", 'Pos'), ("('TUZ', 'Tuzla Canton')", 'Tuz'), ("('ZDK', 'Zenica-Doboj Canton')", 'Zdk'), ("('BPO', 'Bosnian-Podrinje Canton Goražde')", 'Bpo'), ("('SBK', 'Central Bosnia Canton')", 'Sbk'), ("('HN', 'Herzegovina-Neretva Canton')", 'Hn'), ("('HB', 'Herzeg-Bosnian Canton')", 'Hb'), ("('SA', 'Sarajevo Canton')", 'Sa'), ('ZHK', 'Western Herzegovina Canton')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='entity',
            field=models.CharField(choices=[("('RS', 'Republic of Srpska')", 'Rs'), ("('FBiH', 'Federation of Bosnia and Herzegovina')", 'Fbih'), ('BD', 'District Brcko')], default='entitet', max_length=50),
        ),
    ]
