# Generated by Django 4.1.7 on 2023-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_alter_solarpanel_canton_alter_solarpanel_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpanel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='solarpaneldocuments/'),
        ),
        migrations.AlterField(
            model_name='windpowerplant',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='windpowerplantdocuments/'),
        ),
    ]
